services:
  torrent-updater:
    build: .
    container_name: torrent-updater
    network_mode: host
    dns:
      - 192.0.2.1
    restart: always
    env_file:
      - .env
    environment:
      - CHECK_INTERVAL=1
      - CHECK_INTERVAL_UNIT=hours
      - RUN_ON_STARTUP=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/data/cache:/opt/data/cache
      - /tmp/jellyfin.db:/tmp/jellyfin.db:ro
      - /mnt/media/movies:/mnt/media/movies
      - /mnt/media/series:/mnt/media/series
    shm_size: 2g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
